services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - middle_api
    networks:
      - myinternalnetwork

  middle_api:
    build:
      context: ./my_middle_API
    env_file:
      - storage/secrets/secrets_database.env
    ports:
      - "8000:8000"
      - "7000:7000"
    networks:
      - myinternalnetwork

  mailpit:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    depends_on:
      - frontend
    networks:
      - myinternalnetwork

networks:
  myinternalnetwork:
