services:
  db:
    build: ./storage/postgres
    env_file:
      - storage/secrets/secrets_database.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - myinternalnetwork

  pgadmin:
    build:
      context: .
      dockerfile: pgadmin/Dockerfile
    env_file:
      - storage/secrets/secrets_database.env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - myinternalnetwork

networks:
  myinternalnetwork:
    external: true

volumes:
  db_data:
