services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - middle_api
    networks:
      - myinternalnetwork

  middle_api:
    build:
      context: ./my_middle_API
    env_file:
      - storage/secrets/secrets_database.env
    ports:
      - "8000:8000"
      - "7000:7000"
    networks:
      - myinternalnetwork

  mailpit:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    depends_on:
      - frontend
    networks:
      - myinternalnetwork

  dashapp:
    build:
      context: ./my_middle_API
      dockerfile: DashApp/Dockerfile
    container_name: dash-app
    ports:
      - "8050:8050"
    environment:
      - BACKEND_URL=http://middle_api:8000
    # volumes:
    #   - ./reports:/app/reports <--- this shouldn't be here at all
    #   - ./static:/app/static <--- this shouldn't be here at all
    #   - ./tool_bridge_mcp_server/sessions:/app/tool_bridge_mcp_server/sessions <---this can't be used
    depends_on:
      middle_api:
        condition: service_started
    networks:
      - myinternalnetwork

networks:
  myinternalnetwork:
    external: true
