services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - middle_api
    networks:
      - myinternalnetwork

  middle_api:
    build:
      context: ./my_middle_API
    env_file:
      - storage/secrets/secrets_database.env
    ports:
      - "8000:8000"
    networks:
      - myinternalnetwork
    depends_on:
      - db

  db:
    build: ./storage/postgres
    env_file:
      - storage/secrets/secrets_database.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - myinternalnetwork

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - storage/secrets/secrets_database.env
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - myinternalnetwork
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: secret_envs
        target: /pgpass

networks:
  myinternalnetwork:


volumes:
  db_data:


configs:
  secret_envs:
    file: storage/secrets/secrets_database.env
  servers.json:
    file: storage/server.json
