version: '3.8'

services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - middle_api
    networks:
      - myinternalnetwork

  middle_api:
    build:
      context: ./my_middle_API
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_KEY: ${API_KEY}
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_SP_PATH: ${FIREBASE_SP_PATH}
    ports:
      - "8000:8000"
    networks:
      - myinternalnetwork
    depends_on:
      - db

  db:
    build: ./storage/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - myinternalnetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ${PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED}
      DATABASE_HOST: ${DATABASE_HOST}
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - myinternalnetwork
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass

networks:
  myinternalnetwork:


volumes:
  db_data:


configs:
  pgpass:
    content: "${DATABASE_HOST}:5432:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}"
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "S Locator Databases",
        "Host": "${DATABASE_HOST}",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "${POSTGRES_USER}",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}
